### ISSUE TITLE
Оптимизируй код

### ISSUE THREAD

**Issue by Red-Cat-Fat** [Rainboom7/TowerDefense#8]
https://github.com/Rainboom7/TowerDefense/blob/49dd56f4b4bc5c37404512f1709c14b4f9f2cad8/Assets/Scripts/Objects/Towers/ArcherTower.cs#L30
Зачем много раз менять неизменяемое значение на одно и тоже? Не проще это сделать 1 раз при инициализации и так оставить?

**Comment by Rainboom7** [comment]
https://github.com/Rainboom7/TowerDefense/commit/d829faca6b9d3ced3e1b3bbd83061fad322ad59d
забыл дописать это в описание коммита
